/*
 * pico-synth: A Raspberry Pi Pico based digital synthesizer.
 *
 * SPDX-FileCopyrightText: 2021-2022 Rafael G. Martins <rafael@rafaelmartins.eng.br>
 * SPDX-License-Identifier: BSD-3-Clause
 */

// this file was generated by generate.py. do not edit!

#pragma once

#include <pico-synth/engine.h>

#define adsr_amplitude 0x00ff
#define adsr_samples_per_cycle 0x0200

static const uint16_t attack_curve[] = {
    0x0000, 0x0000, 0x0001, 0x0002, 0x0003, 0x0004, 0x0004, 0x0005,
    0x0006, 0x0007, 0x0008, 0x0009, 0x0009, 0x000a, 0x000b, 0x000c,
    0x000d, 0x000d, 0x000e, 0x000f, 0x0010, 0x0011, 0x0011, 0x0012,
    0x0013, 0x0014, 0x0015, 0x0015, 0x0016, 0x0017, 0x0018, 0x0019,
    0x0019, 0x001a, 0x001b, 0x001c, 0x001c, 0x001d, 0x001e, 0x001f,
    0x001f, 0x0020, 0x0021, 0x0022, 0x0023, 0x0023, 0x0024, 0x0025,
    0x0026, 0x0026, 0x0027, 0x0028, 0x0029, 0x0029, 0x002a, 0x002b,
    0x002c, 0x002c, 0x002d, 0x002e, 0x002e, 0x002f, 0x0030, 0x0031,
    0x0031, 0x0032, 0x0033, 0x0034, 0x0034, 0x0035, 0x0036, 0x0036,
    0x0037, 0x0038, 0x0039, 0x0039, 0x003a, 0x003b, 0x003b, 0x003c,
    0x003d, 0x003d, 0x003e, 0x003f, 0x0040, 0x0040, 0x0041, 0x0042,
    0x0042, 0x0043, 0x0044, 0x0044, 0x0045, 0x0046, 0x0046, 0x0047,
    0x0048, 0x0048, 0x0049, 0x004a, 0x004a, 0x004b, 0x004c, 0x004c,
    0x004d, 0x004e, 0x004e, 0x004f, 0x0050, 0x0050, 0x0051, 0x0052,
    0x0052, 0x0053, 0x0054, 0x0054, 0x0055, 0x0056, 0x0056, 0x0057,
    0x0058, 0x0058, 0x0059, 0x0059, 0x005a, 0x005b, 0x005b, 0x005c,
    0x005d, 0x005d, 0x005e, 0x005e, 0x005f, 0x0060, 0x0060, 0x0061,
    0x0062, 0x0062, 0x0063, 0x0063, 0x0064, 0x0065, 0x0065, 0x0066,
    0x0066, 0x0067, 0x0068, 0x0068, 0x0069, 0x0069, 0x006a, 0x006b,
    0x006b, 0x006c, 0x006c, 0x006d, 0x006e, 0x006e, 0x006f, 0x006f,
    0x0070, 0x0071, 0x0071, 0x0072, 0x0072, 0x0073, 0x0073, 0x0074,
    0x0075, 0x0075, 0x0076, 0x0076, 0x0077, 0x0078, 0x0078, 0x0079,
    0x0079, 0x007a, 0x007a, 0x007b, 0x007b, 0x007c, 0x007d, 0x007d,
    0x007e, 0x007e, 0x007f, 0x007f, 0x0080, 0x0080, 0x0081, 0x0082,
    0x0082, 0x0083, 0x0083, 0x0084, 0x0084, 0x0085, 0x0085, 0x0086,
    0x0086, 0x0087, 0x0087, 0x0088, 0x0089, 0x0089, 0x008a, 0x008a,
    0x008b, 0x008b, 0x008c, 0x008c, 0x008d, 0x008d, 0x008e, 0x008e,
    0x008f, 0x008f, 0x0090, 0x0090, 0x0091, 0x0091, 0x0092, 0x0092,
    0x0093, 0x0093, 0x0094, 0x0094, 0x0095, 0x0095, 0x0096, 0x0096,
    0x0097, 0x0097, 0x0098, 0x0098, 0x0099, 0x0099, 0x009a, 0x009a,
    0x009b, 0x009b, 0x009c, 0x009c, 0x009d, 0x009d, 0x009e, 0x009e,
    0x009f, 0x009f, 0x00a0, 0x00a0, 0x00a1, 0x00a1, 0x00a2, 0x00a2,
    0x00a3, 0x00a3, 0x00a4, 0x00a4, 0x00a4, 0x00a5, 0x00a5, 0x00a6,
    0x00a6, 0x00a7, 0x00a7, 0x00a8, 0x00a8, 0x00a9, 0x00a9, 0x00aa,
    0x00aa, 0x00aa, 0x00ab, 0x00ab, 0x00ac, 0x00ac, 0x00ad, 0x00ad,
    0x00ae, 0x00ae, 0x00af, 0x00af, 0x00af, 0x00b0, 0x00b0, 0x00b1,
    0x00b1, 0x00b2, 0x00b2, 0x00b2, 0x00b3, 0x00b3, 0x00b4, 0x00b4,
    0x00b5, 0x00b5, 0x00b6, 0x00b6, 0x00b6, 0x00b7, 0x00b7, 0x00b8,
    0x00b8, 0x00b9, 0x00b9, 0x00b9, 0x00ba, 0x00ba, 0x00bb, 0x00bb,
    0x00bb, 0x00bc, 0x00bc, 0x00bd, 0x00bd, 0x00be, 0x00be, 0x00be,
    0x00bf, 0x00bf, 0x00c0, 0x00c0, 0x00c0, 0x00c1, 0x00c1, 0x00c2,
    0x00c2, 0x00c2, 0x00c3, 0x00c3, 0x00c4, 0x00c4, 0x00c4, 0x00c5,
    0x00c5, 0x00c6, 0x00c6, 0x00c6, 0x00c7, 0x00c7, 0x00c8, 0x00c8,
    0x00c8, 0x00c9, 0x00c9, 0x00ca, 0x00ca, 0x00ca, 0x00cb, 0x00cb,
    0x00cb, 0x00cc, 0x00cc, 0x00cd, 0x00cd, 0x00cd, 0x00ce, 0x00ce,
    0x00ce, 0x00cf, 0x00cf, 0x00d0, 0x00d0, 0x00d0, 0x00d1, 0x00d1,
    0x00d1, 0x00d2, 0x00d2, 0x00d3, 0x00d3, 0x00d3, 0x00d4, 0x00d4,
    0x00d4, 0x00d5, 0x00d5, 0x00d5, 0x00d6, 0x00d6, 0x00d6, 0x00d7,
    0x00d7, 0x00d8, 0x00d8, 0x00d8, 0x00d9, 0x00d9, 0x00d9, 0x00da,
    0x00da, 0x00da, 0x00db, 0x00db, 0x00db, 0x00dc, 0x00dc, 0x00dc,
    0x00dd, 0x00dd, 0x00dd, 0x00de, 0x00de, 0x00de, 0x00df, 0x00df,
    0x00e0, 0x00e0, 0x00e0, 0x00e1, 0x00e1, 0x00e1, 0x00e2, 0x00e2,
    0x00e2, 0x00e3, 0x00e3, 0x00e3, 0x00e3, 0x00e4, 0x00e4, 0x00e4,
    0x00e5, 0x00e5, 0x00e5, 0x00e6, 0x00e6, 0x00e6, 0x00e7, 0x00e7,
    0x00e7, 0x00e8, 0x00e8, 0x00e8, 0x00e9, 0x00e9, 0x00e9, 0x00ea,
    0x00ea, 0x00ea, 0x00eb, 0x00eb, 0x00eb, 0x00eb, 0x00ec, 0x00ec,
    0x00ec, 0x00ed, 0x00ed, 0x00ed, 0x00ee, 0x00ee, 0x00ee, 0x00ef,
    0x00ef, 0x00ef, 0x00ef, 0x00f0, 0x00f0, 0x00f0, 0x00f1, 0x00f1,
    0x00f1, 0x00f2, 0x00f2, 0x00f2, 0x00f2, 0x00f3, 0x00f3, 0x00f3,
    0x00f4, 0x00f4, 0x00f4, 0x00f4, 0x00f5, 0x00f5, 0x00f5, 0x00f6,
    0x00f6, 0x00f6, 0x00f6, 0x00f7, 0x00f7, 0x00f7, 0x00f8, 0x00f8,
    0x00f8, 0x00f8, 0x00f9, 0x00f9, 0x00f9, 0x00fa, 0x00fa, 0x00fa,
    0x00fa, 0x00fb, 0x00fb, 0x00fb, 0x00fc, 0x00fc, 0x00fc, 0x00fc,
    0x00fd, 0x00fd, 0x00fd, 0x00fd, 0x00fe, 0x00fe, 0x00fe, 0x00ff,
};

static const uint16_t decay_release_curve[] = {
    0x0000, 0x0001, 0x0003, 0x0004, 0x0006, 0x0007, 0x0009, 0x000a,
    0x000c, 0x000d, 0x000f, 0x0010, 0x0012, 0x0013, 0x0015, 0x0016,
    0x0018, 0x0019, 0x001a, 0x001c, 0x001d, 0x001f, 0x0020, 0x0021,
    0x0023, 0x0024, 0x0025, 0x0027, 0x0028, 0x002a, 0x002b, 0x002c,
    0x002d, 0x002f, 0x0030, 0x0031, 0x0033, 0x0034, 0x0035, 0x0036,
    0x0038, 0x0039, 0x003a, 0x003b, 0x003d, 0x003e, 0x003f, 0x0040,
    0x0041, 0x0043, 0x0044, 0x0045, 0x0046, 0x0047, 0x0048, 0x004a,
    0x004b, 0x004c, 0x004d, 0x004e, 0x004f, 0x0050, 0x0051, 0x0052,
    0x0054, 0x0055, 0x0056, 0x0057, 0x0058, 0x0059, 0x005a, 0x005b,
    0x005c, 0x005d, 0x005e, 0x005f, 0x0060, 0x0061, 0x0062, 0x0063,
    0x0064, 0x0065, 0x0066, 0x0067, 0x0068, 0x0069, 0x006a, 0x006b,
    0x006c, 0x006d, 0x006e, 0x006f, 0x006f, 0x0070, 0x0071, 0x0072,
    0x0073, 0x0074, 0x0075, 0x0076, 0x0077, 0x0078, 0x0078, 0x0079,
    0x007a, 0x007b, 0x007c, 0x007d, 0x007e, 0x007e, 0x007f, 0x0080,
    0x0081, 0x0082, 0x0082, 0x0083, 0x0084, 0x0085, 0x0086, 0x0086,
    0x0087, 0x0088, 0x0089, 0x008a, 0x008a, 0x008b, 0x008c, 0x008d,
    0x008d, 0x008e, 0x008f, 0x008f, 0x0090, 0x0091, 0x0092, 0x0092,
    0x0093, 0x0094, 0x0094, 0x0095, 0x0096, 0x0097, 0x0097, 0x0098,
    0x0099, 0x0099, 0x009a, 0x009b, 0x009b, 0x009c, 0x009d, 0x009d,
    0x009e, 0x009f, 0x009f, 0x00a0, 0x00a0, 0x00a1, 0x00a2, 0x00a2,
    0x00a3, 0x00a4, 0x00a4, 0x00a5, 0x00a5, 0x00a6, 0x00a7, 0x00a7,
    0x00a8, 0x00a8, 0x00a9, 0x00aa, 0x00aa, 0x00ab, 0x00ab, 0x00ac,
    0x00ac, 0x00ad, 0x00ad, 0x00ae, 0x00af, 0x00af, 0x00b0, 0x00b0,
    0x00b1, 0x00b1, 0x00b2, 0x00b2, 0x00b3, 0x00b3, 0x00b4, 0x00b4,
    0x00b5, 0x00b5, 0x00b6, 0x00b6, 0x00b7, 0x00b7, 0x00b8, 0x00b8,
    0x00b9, 0x00b9, 0x00ba, 0x00ba, 0x00bb, 0x00bb, 0x00bc, 0x00bc,
    0x00bd, 0x00bd, 0x00be, 0x00be, 0x00bf, 0x00bf, 0x00bf, 0x00c0,
    0x00c0, 0x00c1, 0x00c1, 0x00c2, 0x00c2, 0x00c3, 0x00c3, 0x00c3,
    0x00c4, 0x00c4, 0x00c5, 0x00c5, 0x00c5, 0x00c6, 0x00c6, 0x00c7,
    0x00c7, 0x00c8, 0x00c8, 0x00c8, 0x00c9, 0x00c9, 0x00ca, 0x00ca,
    0x00ca, 0x00cb, 0x00cb, 0x00cb, 0x00cc, 0x00cc, 0x00cd, 0x00cd,
    0x00cd, 0x00ce, 0x00ce, 0x00ce, 0x00cf, 0x00cf, 0x00cf, 0x00d0,
    0x00d0, 0x00d1, 0x00d1, 0x00d1, 0x00d2, 0x00d2, 0x00d2, 0x00d3,
    0x00d3, 0x00d3, 0x00d4, 0x00d4, 0x00d4, 0x00d5, 0x00d5, 0x00d5,
    0x00d6, 0x00d6, 0x00d6, 0x00d6, 0x00d7, 0x00d7, 0x00d7, 0x00d8,
    0x00d8, 0x00d8, 0x00d9, 0x00d9, 0x00d9, 0x00da, 0x00da, 0x00da,
    0x00da, 0x00db, 0x00db, 0x00db, 0x00dc, 0x00dc, 0x00dc, 0x00dc,
    0x00dd, 0x00dd, 0x00dd, 0x00dd, 0x00de, 0x00de, 0x00de, 0x00df,
    0x00df, 0x00df, 0x00df, 0x00e0, 0x00e0, 0x00e0, 0x00e0, 0x00e1,
    0x00e1, 0x00e1, 0x00e1, 0x00e2, 0x00e2, 0x00e2, 0x00e2, 0x00e3,
    0x00e3, 0x00e3, 0x00e3, 0x00e4, 0x00e4, 0x00e4, 0x00e4, 0x00e5,
    0x00e5, 0x00e5, 0x00e5, 0x00e5, 0x00e6, 0x00e6, 0x00e6, 0x00e6,
    0x00e7, 0x00e7, 0x00e7, 0x00e7, 0x00e7, 0x00e8, 0x00e8, 0x00e8,
    0x00e8, 0x00e8, 0x00e9, 0x00e9, 0x00e9, 0x00e9, 0x00e9, 0x00ea,
    0x00ea, 0x00ea, 0x00ea, 0x00ea, 0x00eb, 0x00eb, 0x00eb, 0x00eb,
    0x00eb, 0x00ec, 0x00ec, 0x00ec, 0x00ec, 0x00ec, 0x00ed, 0x00ed,
    0x00ed, 0x00ed, 0x00ed, 0x00ed, 0x00ee, 0x00ee, 0x00ee, 0x00ee,
    0x00ee, 0x00ef, 0x00ef, 0x00ef, 0x00ef, 0x00ef, 0x00ef, 0x00f0,
    0x00f0, 0x00f0, 0x00f0, 0x00f0, 0x00f0, 0x00f1, 0x00f1, 0x00f1,
    0x00f1, 0x00f1, 0x00f1, 0x00f1, 0x00f2, 0x00f2, 0x00f2, 0x00f2,
    0x00f2, 0x00f2, 0x00f3, 0x00f3, 0x00f3, 0x00f3, 0x00f3, 0x00f3,
    0x00f3, 0x00f4, 0x00f4, 0x00f4, 0x00f4, 0x00f4, 0x00f4, 0x00f4,
    0x00f5, 0x00f5, 0x00f5, 0x00f5, 0x00f5, 0x00f5, 0x00f5, 0x00f5,
    0x00f6, 0x00f6, 0x00f6, 0x00f6, 0x00f6, 0x00f6, 0x00f6, 0x00f6,
    0x00f7, 0x00f7, 0x00f7, 0x00f7, 0x00f7, 0x00f7, 0x00f7, 0x00f7,
    0x00f8, 0x00f8, 0x00f8, 0x00f8, 0x00f8, 0x00f8, 0x00f8, 0x00f8,
    0x00f9, 0x00f9, 0x00f9, 0x00f9, 0x00f9, 0x00f9, 0x00f9, 0x00f9,
    0x00f9, 0x00fa, 0x00fa, 0x00fa, 0x00fa, 0x00fa, 0x00fa, 0x00fa,
    0x00fa, 0x00fa, 0x00fa, 0x00fb, 0x00fb, 0x00fb, 0x00fb, 0x00fb,
    0x00fb, 0x00fb, 0x00fb, 0x00fb, 0x00fb, 0x00fc, 0x00fc, 0x00fc,
    0x00fc, 0x00fc, 0x00fc, 0x00fc, 0x00fc, 0x00fc, 0x00fc, 0x00fc,
    0x00fd, 0x00fd, 0x00fd, 0x00fd, 0x00fd, 0x00fd, 0x00fd, 0x00fd,
    0x00fd, 0x00fd, 0x00fd, 0x00fe, 0x00fe, 0x00fe, 0x00fe, 0x00fe,
    0x00fe, 0x00fe, 0x00fe, 0x00fe, 0x00fe, 0x00fe, 0x00fe, 0x00ff,
};

static const struct {
    const char *description;
    ps_engine_phase_t step;
} times[] = {
    {
        .description = "2 ms",
        .step        = {0x00055555},
    },
    {
        .description = "3 ms",
        .step        = {0x00038e39},
    },
    {
        .description = "4 ms",
        .step        = {0x0002aaab},
    },
    {
        .description = "5 ms",
        .step        = {0x00022222},
    },
    {
        .description = "6 ms",
        .step        = {0x0001c71c},
    },
    {
        .description = "8 ms",
        .step        = {0x00015555},
    },
    {
        .description = "9 ms",
        .step        = {0x00012f68},
    },
    {
        .description = "10 ms",
        .step        = {0x00011111},
    },
    {
        .description = "12 ms",
        .step        = {0x0000e38e},
    },
    {
        .description = "13 ms",
        .step        = {0x0000d20d},
    },
    {
        .description = "15 ms",
        .step        = {0x0000b60b},
    },
    {
        .description = "16 ms",
        .step        = {0x0000aaab},
    },
    {
        .description = "18 ms",
        .step        = {0x000097b4},
    },
    {
        .description = "19 ms",
        .step        = {0x00008fb8},
    },
    {
        .description = "21 ms",
        .step        = {0x00008208},
    },
    {
        .description = "23 ms",
        .step        = {0x000076ba},
    },
    {
        .description = "24 ms",
        .step        = {0x000071c7},
    },
    {
        .description = "26 ms",
        .step        = {0x00006907},
    },
    {
        .description = "28 ms",
        .step        = {0x00006186},
    },
    {
        .description = "30 ms",
        .step        = {0x00005b06},
    },
    {
        .description = "31 ms",
        .step        = {0x00005816},
    },
    {
        .description = "33 ms",
        .step        = {0x000052bf},
    },
    {
        .description = "35 ms",
        .step        = {0x00004e05},
    },
    {
        .description = "37 ms",
        .step        = {0x000049cd},
    },
    {
        .description = "39 ms",
        .step        = {0x00004604},
    },
    {
        .description = "41 ms",
        .step        = {0x0000429a},
    },
    {
        .description = "43 ms",
        .step        = {0x00003f81},
    },
    {
        .description = "46 ms",
        .step        = {0x00003b5d},
    },
    {
        .description = "48 ms",
        .step        = {0x000038e4},
    },
    {
        .description = "50 ms",
        .step        = {0x0000369d},
    },
    {
        .description = "52 ms",
        .step        = {0x00003483},
    },
    {
        .description = "55 ms",
        .step        = {0x000031a6},
    },
    {
        .description = "57 ms",
        .step        = {0x00002fe8},
    },
    {
        .description = "60 ms",
        .step        = {0x00002d83},
    },
    {
        .description = "62 ms",
        .step        = {0x00002c0b},
    },
    {
        .description = "65 ms",
        .step        = {0x00002a03},
    },
    {
        .description = "68 ms",
        .step        = {0x00002828},
    },
    {
        .description = "70 ms",
        .step        = {0x00002702},
    },
    {
        .description = "73 ms",
        .step        = {0x00002568},
    },
    {
        .description = "76 ms",
        .step        = {0x000023ee},
    },
    {
        .description = "79 ms",
        .step        = {0x00002291},
    },
    {
        .description = "82 ms",
        .step        = {0x0000214d},
    },
    {
        .description = "85 ms",
        .step        = {0x00002020},
    },
    {
        .description = "88 ms",
        .step        = {0x00001f08},
    },
    {
        .description = "92 ms",
        .step        = {0x00001dae},
    },
    {
        .description = "95 ms",
        .step        = {0x00001cbe},
    },
    {
        .description = "98 ms",
        .step        = {0x00001bdd},
    },
    {
        .description = "102 ms",
        .step        = {0x00001ac5},
    },
    {
        .description = "106 ms",
        .step        = {0x000019c3},
    },
    {
        .description = "109 ms",
        .step        = {0x0000190d},
    },
    {
        .description = "113 ms",
        .step        = {0x0000182a},
    },
    {
        .description = "117 ms",
        .step        = {0x00001757},
    },
    {
        .description = "121 ms",
        .step        = {0x00001691},
    },
    {
        .description = "125 ms",
        .step        = {0x000015d8},
    },
    {
        .description = "129 ms",
        .step        = {0x0000152b},
    },
    {
        .description = "133 ms",
        .step        = {0x00001488},
    },
    {
        .description = "137 ms",
        .step        = {0x000013ef},
    },
    {
        .description = "142 ms",
        .step        = {0x0000133b},
    },
    {
        .description = "146 ms",
        .step        = {0x000012b4},
    },
    {
        .description = "151 ms",
        .step        = {0x00001215},
    },
    {
        .description = "156 ms",
        .step        = {0x00001181},
    },
    {
        .description = "161 ms",
        .step        = {0x000010f6},
    },
    {
        .description = "166 ms",
        .step        = {0x00001073},
    },
    {
        .description = "171 ms",
        .step        = {0x00000ff8},
    },
    {
        .description = "176 ms",
        .step        = {0x00000f84},
    },
    {
        .description = "181 ms",
        .step        = {0x00000f16},
    },
    {
        .description = "187 ms",
        .step        = {0x00000e9a},
    },
    {
        .description = "192 ms",
        .step        = {0x00000e39},
    },
    {
        .description = "198 ms",
        .step        = {0x00000dcb},
    },
    {
        .description = "204 ms",
        .step        = {0x00000d63},
    },
    {
        .description = "210 ms",
        .step        = {0x00000d01},
    },
    {
        .description = "216 ms",
        .step        = {0x00000ca4},
    },
    {
        .description = "222 ms",
        .step        = {0x00000c4d},
    },
    {
        .description = "229 ms",
        .step        = {0x00000bed},
    },
    {
        .description = "235 ms",
        .step        = {0x00000b9f},
    },
    {
        .description = "242 ms",
        .step        = {0x00000b49},
    },
    {
        .description = "249 ms",
        .step        = {0x00000af7},
    },
    {
        .description = "256 ms",
        .step        = {0x00000aab},
    },
    {
        .description = "263 ms",
        .step        = {0x00000a62},
    },
    {
        .description = "271 ms",
        .step        = {0x00000a14},
    },
    {
        .description = "278 ms",
        .step        = {0x000009d3},
    },
    {
        .description = "286 ms",
        .step        = {0x0000098c},
    },
    {
        .description = "294 ms",
        .step        = {0x0000094a},
    },
    {
        .description = "302 ms",
        .step        = {0x0000090b},
    },
    {
        .description = "310 ms",
        .step        = {0x000008cf},
    },
    {
        .description = "319 ms",
        .step        = {0x0000088f},
    },
    {
        .description = "328 ms",
        .step        = {0x00000853},
    },
    {
        .description = "337 ms",
        .step        = {0x0000081a},
    },
    {
        .description = "346 ms",
        .step        = {0x000007e4},
    },
    {
        .description = "355 ms",
        .step        = {0x000007b1},
    },
    {
        .description = "365 ms",
        .step        = {0x0000077b},
    },
    {
        .description = "375 ms",
        .step        = {0x00000748},
    },
    {
        .description = "385 ms",
        .step        = {0x00000718},
    },
    {
        .description = "395 ms",
        .step        = {0x000006ea},
    },
    {
        .description = "406 ms",
        .step        = {0x000006ba},
    },
    {
        .description = "416 ms",
        .step        = {0x00000690},
    },
    {
        .description = "427 ms",
        .step        = {0x00000665},
    },
    {
        .description = "439 ms",
        .step        = {0x00000638},
    },
    {
        .description = "450 ms",
        .step        = {0x00000611},
    },
    {
        .description = "462 ms",
        .step        = {0x000005e9},
    },
    {
        .description = "474 ms",
        .step        = {0x000005c3},
    },
    {
        .description = "487 ms",
        .step        = {0x0000059b},
    },
    {
        .description = "500 ms",
        .step        = {0x00000576},
    },
    {
        .description = "513 ms",
        .step        = {0x00000553},
    },
    {
        .description = "526 ms",
        .step        = {0x00000531},
    },
    {
        .description = "540 ms",
        .step        = {0x0000050f},
    },
    {
        .description = "554 ms",
        .step        = {0x000004ee},
    },
    {
        .description = "568 ms",
        .step        = {0x000004cf},
    },
    {
        .description = "583 ms",
        .step        = {0x000004af},
    },
    {
        .description = "598 ms",
        .step        = {0x00000491},
    },
    {
        .description = "613 ms",
        .step        = {0x00000474},
    },
    {
        .description = "629 ms",
        .step        = {0x00000457},
    },
    {
        .description = "645 ms",
        .step        = {0x0000043c},
    },
    {
        .description = "661 ms",
        .step        = {0x00000422},
    },
    {
        .description = "678 ms",
        .step        = {0x00000407},
    },
    {
        .description = "696 ms",
        .step        = {0x000003ec},
    },
    {
        .description = "713 ms",
        .step        = {0x000003d4},
    },
    {
        .description = "731 ms",
        .step        = {0x000003bc},
    },
    {
        .description = "750 ms",
        .step        = {0x000003a4},
    },
    {
        .description = "769 ms",
        .step        = {0x0000038d},
    },
    {
        .description = "788 ms",
        .step        = {0x00000377},
    },
    {
        .description = "808 ms",
        .step        = {0x00000361},
    },
    {
        .description = "829 ms",
        .step        = {0x0000034b},
    },
    {
        .description = "850 ms",
        .step        = {0x00000336},
    },
    {
        .description = "871 ms",
        .step        = {0x00000323},
    },
    {
        .description = "893 ms",
        .step        = {0x0000030f},
    },
    {
        .description = "915 ms",
        .step        = {0x000002fc},
    },
    {
        .description = "938 ms",
        .step        = {0x000002e9},
    },
    {
        .description = "962 ms",
        .step        = {0x000002d7},
    },
    {
        .description = "986 ms",
        .step        = {0x000002c5},
    },
    {
        .description = "1.01 s",
        .step        = {0x000002b4},
    },
    {
        .description = "1.04 s",
        .step        = {0x000002a3},
    },
    {
        .description = "1.06 s",
        .step        = {0x00000293},
    },
    {
        .description = "1.09 s",
        .step        = {0x00000283},
    },
    {
        .description = "1.11 s",
        .step        = {0x00000273},
    },
    {
        .description = "1.14 s",
        .step        = {0x00000264},
    },
    {
        .description = "1.17 s",
        .step        = {0x00000255},
    },
    {
        .description = "1.20 s",
        .step        = {0x00000247},
    },
    {
        .description = "1.23 s",
        .step        = {0x00000238},
    },
    {
        .description = "1.26 s",
        .step        = {0x0000022b},
    },
    {
        .description = "1.29 s",
        .step        = {0x0000021d},
    },
    {
        .description = "1.32 s",
        .step        = {0x00000210},
    },
    {
        .description = "1.36 s",
        .step        = {0x00000204},
    },
    {
        .description = "1.39 s",
        .step        = {0x000001f7},
    },
    {
        .description = "1.42 s",
        .step        = {0x000001eb},
    },
    {
        .description = "1.46 s",
        .step        = {0x000001df},
    },
    {
        .description = "1.49 s",
        .step        = {0x000001d4},
    },
    {
        .description = "1.53 s",
        .step        = {0x000001c9},
    },
    {
        .description = "1.57 s",
        .step        = {0x000001be},
    },
    {
        .description = "1.61 s",
        .step        = {0x000001b3},
    },
    {
        .description = "1.65 s",
        .step        = {0x000001a8},
    },
    {
        .description = "1.69 s",
        .step        = {0x0000019e},
    },
    {
        .description = "1.73 s",
        .step        = {0x00000195},
    },
    {
        .description = "1.77 s",
        .step        = {0x0000018b},
    },
    {
        .description = "1.81 s",
        .step        = {0x00000181},
    },
    {
        .description = "1.86 s",
        .step        = {0x00000178},
    },
    {
        .description = "1.90 s",
        .step        = {0x0000016f},
    },
    {
        .description = "1.95 s",
        .step        = {0x00000166},
    },
    {
        .description = "2.00 s",
        .step        = {0x0000015e},
    },
    {
        .description = "2.05 s",
        .step        = {0x00000156},
    },
    {
        .description = "2.10 s",
        .step        = {0x0000014e},
    },
    {
        .description = "2.15 s",
        .step        = {0x00000146},
    },
    {
        .description = "2.20 s",
        .step        = {0x0000013e},
    },
    {
        .description = "2.25 s",
        .step        = {0x00000136},
    },
    {
        .description = "2.31 s",
        .step        = {0x0000012f},
    },
    {
        .description = "2.36 s",
        .step        = {0x00000128},
    },
    {
        .description = "2.42 s",
        .step        = {0x00000121},
    },
    {
        .description = "2.48 s",
        .step        = {0x0000011a},
    },
    {
        .description = "2.54 s",
        .step        = {0x00000113},
    },
    {
        .description = "2.60 s",
        .step        = {0x0000010d},
    },
    {
        .description = "2.67 s",
        .step        = {0x00000106},
    },
    {
        .description = "2.73 s",
        .step        = {0x00000100},
    },
    {
        .description = "2.80 s",
        .step        = {0x000000fa},
    },
    {
        .description = "2.86 s",
        .step        = {0x000000f4},
    },
    {
        .description = "2.93 s",
        .step        = {0x000000ee},
    },
    {
        .description = "3.00 s",
        .step        = {0x000000e9},
    },
    {
        .description = "3.08 s",
        .step        = {0x000000e3},
    },
    {
        .description = "3.15 s",
        .step        = {0x000000de},
    },
    {
        .description = "3.23 s",
        .step        = {0x000000d9},
    },
    {
        .description = "3.31 s",
        .step        = {0x000000d4},
    },
    {
        .description = "3.38 s",
        .step        = {0x000000cf},
    },
    {
        .description = "3.47 s",
        .step        = {0x000000ca},
    },
    {
        .description = "3.55 s",
        .step        = {0x000000c5},
    },
    {
        .description = "3.64 s",
        .step        = {0x000000c0},
    },
    {
        .description = "3.72 s",
        .step        = {0x000000bc},
    },
    {
        .description = "3.81 s",
        .step        = {0x000000b7},
    },
    {
        .description = "3.90 s",
        .step        = {0x000000b3},
    },
    {
        .description = "4.00 s",
        .step        = {0x000000af},
    },
    {
        .description = "4.10 s",
        .step        = {0x000000ab},
    },
    {
        .description = "4.19 s",
        .step        = {0x000000a7},
    },
    {
        .description = "4.29 s",
        .step        = {0x000000a3},
    },
    {
        .description = "4.40 s",
        .step        = {0x0000009f},
    },
    {
        .description = "4.50 s",
        .step        = {0x0000009b},
    },
    {
        .description = "4.61 s",
        .step        = {0x00000098},
    },
    {
        .description = "4.72 s",
        .step        = {0x00000094},
    },
    {
        .description = "4.84 s",
        .step        = {0x00000090},
    },
    {
        .description = "4.95 s",
        .step        = {0x0000008d},
    },
    {
        .description = "5.07 s",
        .step        = {0x0000008a},
    },
    {
        .description = "5.20 s",
        .step        = {0x00000087},
    },
    {
        .description = "5.32 s",
        .step        = {0x00000083},
    },
    {
        .description = "5.45 s",
        .step        = {0x00000080},
    },
    {
        .description = "5.58 s",
        .step        = {0x0000007d},
    },
    {
        .description = "5.71 s",
        .step        = {0x0000007a},
    },
    {
        .description = "5.85 s",
        .step        = {0x00000077},
    },
    {
        .description = "5.99 s",
        .step        = {0x00000075},
    },
    {
        .description = "6.13 s",
        .step        = {0x00000072},
    },
    {
        .description = "6.28 s",
        .step        = {0x0000006f},
    },
    {
        .description = "6.43 s",
        .step        = {0x0000006d},
    },
    {
        .description = "6.59 s",
        .step        = {0x0000006a},
    },
    {
        .description = "6.74 s",
        .step        = {0x00000068},
    },
    {
        .description = "6.91 s",
        .step        = {0x00000065},
    },
    {
        .description = "7.07 s",
        .step        = {0x00000063},
    },
    {
        .description = "7.24 s",
        .step        = {0x00000061},
    },
    {
        .description = "7.41 s",
        .step        = {0x0000005e},
    },
    {
        .description = "7.59 s",
        .step        = {0x0000005c},
    },
    {
        .description = "7.77 s",
        .step        = {0x0000005a},
    },
    {
        .description = "7.96 s",
        .step        = {0x00000058},
    },
    {
        .description = "8.15 s",
        .step        = {0x00000056},
    },
    {
        .description = "8.35 s",
        .step        = {0x00000054},
    },
    {
        .description = "8.55 s",
        .step        = {0x00000052},
    },
    {
        .description = "8.75 s",
        .step        = {0x00000050},
    },
    {
        .description = "8.96 s",
        .step        = {0x0000004e},
    },
    {
        .description = "9.17 s",
        .step        = {0x0000004c},
    },
    {
        .description = "9.39 s",
        .step        = {0x0000004a},
    },
    {
        .description = "9.62 s",
        .step        = {0x00000049},
    },
    {
        .description = "9.85 s",
        .step        = {0x00000047},
    },
    {
        .description = "10.08 s",
        .step        = {0x00000045},
    },
    {
        .description = "10.33 s",
        .step        = {0x00000044},
    },
    {
        .description = "10.57 s",
        .step        = {0x00000042},
    },
    {
        .description = "10.83 s",
        .step        = {0x00000041},
    },
    {
        .description = "11.08 s",
        .step        = {0x0000003f},
    },
    {
        .description = "11.35 s",
        .step        = {0x0000003e},
    },
    {
        .description = "11.62 s",
        .step        = {0x0000003c},
    },
    {
        .description = "11.90 s",
        .step        = {0x0000003b},
    },
    {
        .description = "12.18 s",
        .step        = {0x00000039},
    },
    {
        .description = "12.47 s",
        .step        = {0x00000038},
    },
    {
        .description = "12.77 s",
        .step        = {0x00000037},
    },
    {
        .description = "13.08 s",
        .step        = {0x00000035},
    },
    {
        .description = "13.39 s",
        .step        = {0x00000034},
    },
    {
        .description = "13.71 s",
        .step        = {0x00000033},
    },
    {
        .description = "14.04 s",
        .step        = {0x00000032},
    },
    {
        .description = "14.37 s",
        .step        = {0x00000031},
    },
    {
        .description = "14.72 s",
        .step        = {0x00000030},
    },
    {
        .description = "15.07 s",
        .step        = {0x0000002e},
    },
    {
        .description = "15.43 s",
        .step        = {0x0000002d},
    },
    {
        .description = "15.80 s",
        .step        = {0x0000002c},
    },
    {
        .description = "16.17 s",
        .step        = {0x0000002b},
    },
    {
        .description = "16.56 s",
        .step        = {0x0000002a},
    },
    {
        .description = "16.95 s",
        .step        = {0x00000029},
    },
    {
        .description = "17.36 s",
        .step        = {0x00000028},
    },
    {
        .description = "17.77 s",
        .step        = {0x00000027},
    },
    {
        .description = "18.20 s",
        .step        = {0x00000026},
    },
    {
        .description = "18.63 s",
        .step        = {0x00000026},
    },
    {
        .description = "19.08 s",
        .step        = {0x00000025},
    },
    {
        .description = "19.53 s",
        .step        = {0x00000024},
    },
    {
        .description = "20.00 s",
        .step        = {0x00000023},
    },
};
