// this file was generated by generate.py. do not edit!

#pragma once

#include <pico-synth/engine.h>

#define notes_last 127

static const note_t notes[] = {
    {
        .id   = 0,
        .name = "C-1",
        .step = {
            .pint  = 0x0001,
            .pfrac = 0x84cb,
        },
    },
    {
        .id   = 1,
        .name = "C#-1",
        .step = {
            .pint  = 0x0001,
            .pfrac = 0x9bea,
        },
    },
    {
        .id   = 2,
        .name = "D-1",
        .step = {
            .pint  = 0x0001,
            .pfrac = 0xb468,
        },
    },
    {
        .id   = 3,
        .name = "D#-1",
        .step = {
            .pint  = 0x0001,
            .pfrac = 0xce5b,
        },
    },
    {
        .id   = 4,
        .name = "E-1",
        .step = {
            .pint  = 0x0001,
            .pfrac = 0xe9da,
        },
    },
    {
        .id   = 5,
        .name = "F-1",
        .step = {
            .pint  = 0x0002,
            .pfrac = 0x06fa,
        },
    },
    {
        .id   = 6,
        .name = "F#-1",
        .step = {
            .pint  = 0x0002,
            .pfrac = 0x25d7,
        },
    },
    {
        .id   = 7,
        .name = "G-1",
        .step = {
            .pint  = 0x0002,
            .pfrac = 0x4689,
        },
    },
    {
        .id   = 8,
        .name = "G#-1",
        .step = {
            .pint  = 0x0002,
            .pfrac = 0x692c,
        },
    },
    {
        .id   = 9,
        .name = "A-1",
        .step = {
            .pint  = 0x0002,
            .pfrac = 0x8ddf,
        },
    },
    {
        .id   = 10,
        .name = "A#-1",
        .step = {
            .pint  = 0x0002,
            .pfrac = 0xb4c1,
        },
    },
    {
        .id   = 11,
        .name = "B-1",
        .step = {
            .pint  = 0x0002,
            .pfrac = 0xddf2,
        },
    },
    {
        .id   = 12,
        .name = "C0",
        .step = {
            .pint  = 0x0003,
            .pfrac = 0x0997,
        },
    },
    {
        .id   = 13,
        .name = "C#0",
        .step = {
            .pint  = 0x0003,
            .pfrac = 0x37d4,
        },
    },
    {
        .id   = 14,
        .name = "D0",
        .step = {
            .pint  = 0x0003,
            .pfrac = 0x68d1,
        },
    },
    {
        .id   = 15,
        .name = "D#0",
        .step = {
            .pint  = 0x0003,
            .pfrac = 0x9cb7,
        },
    },
    {
        .id   = 16,
        .name = "E0",
        .step = {
            .pint  = 0x0003,
            .pfrac = 0xd3b4,
        },
    },
    {
        .id   = 17,
        .name = "F0",
        .step = {
            .pint  = 0x0004,
            .pfrac = 0x0df5,
        },
    },
    {
        .id   = 18,
        .name = "F#0",
        .step = {
            .pint  = 0x0004,
            .pfrac = 0x4bae,
        },
    },
    {
        .id   = 19,
        .name = "G0",
        .step = {
            .pint  = 0x0004,
            .pfrac = 0x8d12,
        },
    },
    {
        .id   = 20,
        .name = "G#0",
        .step = {
            .pint  = 0x0004,
            .pfrac = 0xd259,
        },
    },
    {
        .id   = 21,
        .name = "A0",
        .step = {
            .pint  = 0x0005,
            .pfrac = 0x1bbf,
        },
    },
    {
        .id   = 22,
        .name = "A#0",
        .step = {
            .pint  = 0x0005,
            .pfrac = 0x6982,
        },
    },
    {
        .id   = 23,
        .name = "B0",
        .step = {
            .pint  = 0x0005,
            .pfrac = 0xbbe5,
        },
    },
    {
        .id   = 24,
        .name = "C1",
        .step = {
            .pint  = 0x0006,
            .pfrac = 0x132e,
        },
    },
    {
        .id   = 25,
        .name = "C#1",
        .step = {
            .pint  = 0x0006,
            .pfrac = 0x6fa8,
        },
    },
    {
        .id   = 26,
        .name = "D1",
        .step = {
            .pint  = 0x0006,
            .pfrac = 0xd1a2,
        },
    },
    {
        .id   = 27,
        .name = "D#1",
        .step = {
            .pint  = 0x0007,
            .pfrac = 0x396f,
        },
    },
    {
        .id   = 28,
        .name = "E1",
        .step = {
            .pint  = 0x0007,
            .pfrac = 0xa768,
        },
    },
    {
        .id   = 29,
        .name = "F1",
        .step = {
            .pint  = 0x0008,
            .pfrac = 0x1beb,
        },
    },
    {
        .id   = 30,
        .name = "F#1",
        .step = {
            .pint  = 0x0008,
            .pfrac = 0x975c,
        },
    },
    {
        .id   = 31,
        .name = "G1",
        .step = {
            .pint  = 0x0009,
            .pfrac = 0x1a24,
        },
    },
    {
        .id   = 32,
        .name = "G#1",
        .step = {
            .pint  = 0x0009,
            .pfrac = 0xa4b2,
        },
    },
    {
        .id   = 33,
        .name = "A1",
        .step = {
            .pint  = 0x000a,
            .pfrac = 0x377e,
        },
    },
    {
        .id   = 34,
        .name = "A#1",
        .step = {
            .pint  = 0x000a,
            .pfrac = 0xd305,
        },
    },
    {
        .id   = 35,
        .name = "B1",
        .step = {
            .pint  = 0x000b,
            .pfrac = 0x77cb,
        },
    },
    {
        .id   = 36,
        .name = "C2",
        .step = {
            .pint  = 0x000c,
            .pfrac = 0x265d,
        },
    },
    {
        .id   = 37,
        .name = "C#2",
        .step = {
            .pint  = 0x000c,
            .pfrac = 0xdf51,
        },
    },
    {
        .id   = 38,
        .name = "D2",
        .step = {
            .pint  = 0x000d,
            .pfrac = 0xa344,
        },
    },
    {
        .id   = 39,
        .name = "D#2",
        .step = {
            .pint  = 0x000e,
            .pfrac = 0x72de,
        },
    },
    {
        .id   = 40,
        .name = "E2",
        .step = {
            .pint  = 0x000f,
            .pfrac = 0x4ed0,
        },
    },
    {
        .id   = 41,
        .name = "F2",
        .step = {
            .pint  = 0x0010,
            .pfrac = 0x37d7,
        },
    },
    {
        .id   = 42,
        .name = "F#2",
        .step = {
            .pint  = 0x0011,
            .pfrac = 0x2eb8,
        },
    },
    {
        .id   = 43,
        .name = "G2",
        .step = {
            .pint  = 0x0012,
            .pfrac = 0x3448,
        },
    },
    {
        .id   = 44,
        .name = "G#2",
        .step = {
            .pint  = 0x0013,
            .pfrac = 0x4965,
        },
    },
    {
        .id   = 45,
        .name = "A2",
        .step = {
            .pint  = 0x0014,
            .pfrac = 0x6efd,
        },
    },
    {
        .id   = 46,
        .name = "A#2",
        .step = {
            .pint  = 0x0015,
            .pfrac = 0xa60a,
        },
    },
    {
        .id   = 47,
        .name = "B2",
        .step = {
            .pint  = 0x0016,
            .pfrac = 0xef96,
        },
    },
    {
        .id   = 48,
        .name = "C3",
        .step = {
            .pint  = 0x0018,
            .pfrac = 0x4cbb,
        },
    },
    {
        .id   = 49,
        .name = "C#3",
        .step = {
            .pint  = 0x0019,
            .pfrac = 0xbea2,
        },
    },
    {
        .id   = 50,
        .name = "D3",
        .step = {
            .pint  = 0x001b,
            .pfrac = 0x4689,
        },
    },
    {
        .id   = 51,
        .name = "D#3",
        .step = {
            .pint  = 0x001c,
            .pfrac = 0xe5bd,
        },
    },
    {
        .id   = 52,
        .name = "E3",
        .step = {
            .pint  = 0x001e,
            .pfrac = 0x9da1,
        },
    },
    {
        .id   = 53,
        .name = "F3",
        .step = {
            .pint  = 0x0020,
            .pfrac = 0x6fae,
        },
    },
    {
        .id   = 54,
        .name = "F#3",
        .step = {
            .pint  = 0x0022,
            .pfrac = 0x5d71,
        },
    },
    {
        .id   = 55,
        .name = "G3",
        .step = {
            .pint  = 0x0024,
            .pfrac = 0x6891,
        },
    },
    {
        .id   = 56,
        .name = "G#3",
        .step = {
            .pint  = 0x0026,
            .pfrac = 0x92cb,
        },
    },
    {
        .id   = 57,
        .name = "A3",
        .step = {
            .pint  = 0x0028,
            .pfrac = 0xddfb,
        },
    },
    {
        .id   = 58,
        .name = "A#3",
        .step = {
            .pint  = 0x002b,
            .pfrac = 0x4c15,
        },
    },
    {
        .id   = 59,
        .name = "B3",
        .step = {
            .pint  = 0x002d,
            .pfrac = 0xdf2d,
        },
    },
    {
        .id   = 60,
        .name = "C4",
        .step = {
            .pint  = 0x0030,
            .pfrac = 0x9976,
        },
    },
    {
        .id   = 61,
        .name = "C#4",
        .step = {
            .pint  = 0x0033,
            .pfrac = 0x7d45,
        },
    },
    {
        .id   = 62,
        .name = "D4",
        .step = {
            .pint  = 0x0036,
            .pfrac = 0x8d12,
        },
    },
    {
        .id   = 63,
        .name = "D#4",
        .step = {
            .pint  = 0x0039,
            .pfrac = 0xcb7a,
        },
    },
    {
        .id   = 64,
        .name = "E4",
        .step = {
            .pint  = 0x003d,
            .pfrac = 0x3b43,
        },
    },
    {
        .id   = 65,
        .name = "F4",
        .step = {
            .pint  = 0x0040,
            .pfrac = 0xdf5c,
        },
    },
    {
        .id   = 66,
        .name = "F#4",
        .step = {
            .pint  = 0x0044,
            .pfrac = 0xbae3,
        },
    },
    {
        .id   = 67,
        .name = "G4",
        .step = {
            .pint  = 0x0048,
            .pfrac = 0xd122,
        },
    },
    {
        .id   = 68,
        .name = "G#4",
        .step = {
            .pint  = 0x004d,
            .pfrac = 0x2597,
        },
    },
    {
        .id   = 69,
        .name = "A4",
        .step = {
            .pint  = 0x0051,
            .pfrac = 0xbbf7,
        },
    },
    {
        .id   = 70,
        .name = "A#4",
        .step = {
            .pint  = 0x0056,
            .pfrac = 0x982b,
        },
    },
    {
        .id   = 71,
        .name = "B4",
        .step = {
            .pint  = 0x005b,
            .pfrac = 0xbe5b,
        },
    },
    {
        .id   = 72,
        .name = "C5",
        .step = {
            .pint  = 0x0061,
            .pfrac = 0x32ed,
        },
    },
    {
        .id   = 73,
        .name = "C#5",
        .step = {
            .pint  = 0x0066,
            .pfrac = 0xfa8b,
        },
    },
    {
        .id   = 74,
        .name = "D5",
        .step = {
            .pint  = 0x006d,
            .pfrac = 0x1a24,
        },
    },
    {
        .id   = 75,
        .name = "D#5",
        .step = {
            .pint  = 0x0073,
            .pfrac = 0x96f4,
        },
    },
    {
        .id   = 76,
        .name = "E5",
        .step = {
            .pint  = 0x007a,
            .pfrac = 0x7686,
        },
    },
    {
        .id   = 77,
        .name = "F5",
        .step = {
            .pint  = 0x0081,
            .pfrac = 0xbeb9,
        },
    },
    {
        .id   = 78,
        .name = "F#5",
        .step = {
            .pint  = 0x0089,
            .pfrac = 0x75c6,
        },
    },
    {
        .id   = 79,
        .name = "G5",
        .step = {
            .pint  = 0x0091,
            .pfrac = 0xa244,
        },
    },
    {
        .id   = 80,
        .name = "G#5",
        .step = {
            .pint  = 0x009a,
            .pfrac = 0x4b2f,
        },
    },
    {
        .id   = 81,
        .name = "A5",
        .step = {
            .pint  = 0x00a3,
            .pfrac = 0x77ee,
        },
    },
    {
        .id   = 82,
        .name = "A#5",
        .step = {
            .pint  = 0x00ad,
            .pfrac = 0x3056,
        },
    },
    {
        .id   = 83,
        .name = "B5",
        .step = {
            .pint  = 0x00b7,
            .pfrac = 0x7cb6,
        },
    },
    {
        .id   = 84,
        .name = "C6",
        .step = {
            .pint  = 0x00c2,
            .pfrac = 0x65db,
        },
    },
    {
        .id   = 85,
        .name = "C#6",
        .step = {
            .pint  = 0x00cd,
            .pfrac = 0xf516,
        },
    },
    {
        .id   = 86,
        .name = "D6",
        .step = {
            .pint  = 0x00da,
            .pfrac = 0x3449,
        },
    },
    {
        .id   = 87,
        .name = "D#6",
        .step = {
            .pint  = 0x00e7,
            .pfrac = 0x2de9,
        },
    },
    {
        .id   = 88,
        .name = "E6",
        .step = {
            .pint  = 0x00f4,
            .pfrac = 0xed0d,
        },
    },
    {
        .id   = 89,
        .name = "F6",
        .step = {
            .pint  = 0x0103,
            .pfrac = 0x7d73,
        },
    },
    {
        .id   = 90,
        .name = "F#6",
        .step = {
            .pint  = 0x0112,
            .pfrac = 0xeb8c,
        },
    },
    {
        .id   = 91,
        .name = "G6",
        .step = {
            .pint  = 0x0123,
            .pfrac = 0x4489,
        },
    },
    {
        .id   = 92,
        .name = "G#6",
        .step = {
            .pint  = 0x0134,
            .pfrac = 0x965f,
        },
    },
    {
        .id   = 93,
        .name = "A6",
        .step = {
            .pint  = 0x0146,
            .pfrac = 0xefdc,
        },
    },
    {
        .id   = 94,
        .name = "A#6",
        .step = {
            .pint  = 0x015a,
            .pfrac = 0x60ad,
        },
    },
    {
        .id   = 95,
        .name = "B6",
        .step = {
            .pint  = 0x016e,
            .pfrac = 0xf96d,
        },
    },
    {
        .id   = 96,
        .name = "C7",
        .step = {
            .pint  = 0x0184,
            .pfrac = 0xcbb6,
        },
    },
    {
        .id   = 97,
        .name = "C#7",
        .step = {
            .pint  = 0x019b,
            .pfrac = 0xea2d,
        },
    },
    {
        .id   = 98,
        .name = "D7",
        .step = {
            .pint  = 0x01b4,
            .pfrac = 0x6892,
        },
    },
    {
        .id   = 99,
        .name = "D#7",
        .step = {
            .pint  = 0x01ce,
            .pfrac = 0x5bd2,
        },
    },
    {
        .id   = 100,
        .name = "E7",
        .step = {
            .pint  = 0x01e9,
            .pfrac = 0xda1a,
        },
    },
    {
        .id   = 101,
        .name = "F7",
        .step = {
            .pint  = 0x0206,
            .pfrac = 0xfae6,
        },
    },
    {
        .id   = 102,
        .name = "F#7",
        .step = {
            .pint  = 0x0225,
            .pfrac = 0xd719,
        },
    },
    {
        .id   = 103,
        .name = "G7",
        .step = {
            .pint  = 0x0246,
            .pfrac = 0x8912,
        },
    },
    {
        .id   = 104,
        .name = "G#7",
        .step = {
            .pint  = 0x0269,
            .pfrac = 0x2cbf,
        },
    },
    {
        .id   = 105,
        .name = "A7",
        .step = {
            .pint  = 0x028d,
            .pfrac = 0xdfb9,
        },
    },
    {
        .id   = 106,
        .name = "A#7",
        .step = {
            .pint  = 0x02b4,
            .pfrac = 0xc15a,
        },
    },
    {
        .id   = 107,
        .name = "B7",
        .step = {
            .pint  = 0x02dd,
            .pfrac = 0xf2db,
        },
    },
    {
        .id   = 108,
        .name = "C8",
        .step = {
            .pint  = 0x0309,
            .pfrac = 0x976d,
        },
    },
    {
        .id   = 109,
        .name = "C#8",
        .step = {
            .pint  = 0x0337,
            .pfrac = 0xd45b,
        },
    },
    {
        .id   = 110,
        .name = "D8",
        .step = {
            .pint  = 0x0368,
            .pfrac = 0xd125,
        },
    },
    {
        .id   = 111,
        .name = "D#8",
        .step = {
            .pint  = 0x039c,
            .pfrac = 0xb7a5,
        },
    },
    {
        .id   = 112,
        .name = "E8",
        .step = {
            .pint  = 0x03d3,
            .pfrac = 0xb434,
        },
    },
    {
        .id   = 113,
        .name = "F8",
        .step = {
            .pint  = 0x040d,
            .pfrac = 0xf5cc,
        },
    },
    {
        .id   = 114,
        .name = "F#8",
        .step = {
            .pint  = 0x044b,
            .pfrac = 0xae33,
        },
    },
    {
        .id   = 115,
        .name = "G8",
        .step = {
            .pint  = 0x048d,
            .pfrac = 0x1225,
        },
    },
    {
        .id   = 116,
        .name = "G#8",
        .step = {
            .pint  = 0x04d2,
            .pfrac = 0x597f,
        },
    },
    {
        .id   = 117,
        .name = "A8",
        .step = {
            .pint  = 0x051b,
            .pfrac = 0xbf72,
        },
    },
    {
        .id   = 118,
        .name = "A#8",
        .step = {
            .pint  = 0x0569,
            .pfrac = 0x82b5,
        },
    },
    {
        .id   = 119,
        .name = "B8",
        .step = {
            .pint  = 0x05bb,
            .pfrac = 0xe5b7,
        },
    },
    {
        .id   = 120,
        .name = "C9",
        .step = {
            .pint  = 0x0613,
            .pfrac = 0x2edb,
        },
    },
    {
        .id   = 121,
        .name = "C#9",
        .step = {
            .pint  = 0x066f,
            .pfrac = 0xa8b6,
        },
    },
    {
        .id   = 122,
        .name = "D9",
        .step = {
            .pint  = 0x06d1,
            .pfrac = 0xa24a,
        },
    },
    {
        .id   = 123,
        .name = "D#9",
        .step = {
            .pint  = 0x0739,
            .pfrac = 0x6f4b,
        },
    },
    {
        .id   = 124,
        .name = "E9",
        .step = {
            .pint  = 0x07a7,
            .pfrac = 0x6868,
        },
    },
    {
        .id   = 125,
        .name = "F9",
        .step = {
            .pint  = 0x081b,
            .pfrac = 0xeb99,
        },
    },
    {
        .id   = 126,
        .name = "F#9",
        .step = {
            .pint  = 0x0897,
            .pfrac = 0x5c67,
        },
    },
    {
        .id   = 127,
        .name = "G9",
        .step = {
            .pint  = 0x091a,
            .pfrac = 0x244a,
        },
    },
};
