/*
 * pico-synth: A Raspberry Pi Pico based digital synthesizer.
 *
 * SPDX-FileCopyrightText: 2021-2022 Rafael G. Martins <rafael@rafaelmartins.eng.br>
 * SPDX-License-Identifier: BSD-3-Clause
 */

// this file was generated by generate.py. do not edit!

#pragma once

#include <pico-synth/engine.h>

#define notes_last 127

static const ps_engine_note_t notes[] = {
    {
        .id        = 0,
        .name      = "C-1",
        .step.data = 0x00001653,
    },
    {
        .id        = 1,
        .name      = "C#-1",
        .step.data = 0x000017a7,
    },
    {
        .id        = 2,
        .name      = "D-1",
        .step.data = 0x0000190f,
    },
    {
        .id        = 3,
        .name      = "D#-1",
        .step.data = 0x00001a8c,
    },
    {
        .id        = 4,
        .name      = "E-1",
        .step.data = 0x00001c20,
    },
    {
        .id        = 5,
        .name      = "F-1",
        .step.data = 0x00001dcd,
    },
    {
        .id        = 6,
        .name      = "F#-1",
        .step.data = 0x00001f92,
    },
    {
        .id        = 7,
        .name      = "G-1",
        .step.data = 0x00002173,
    },
    {
        .id        = 8,
        .name      = "G#-1",
        .step.data = 0x00002370,
    },
    {
        .id        = 9,
        .name      = "A-1",
        .step.data = 0x0000258b,
    },
    {
        .id        = 10,
        .name      = "A#-1",
        .step.data = 0x000027c7,
    },
    {
        .id        = 11,
        .name      = "B-1",
        .step.data = 0x00002a25,
    },
    {
        .id        = 12,
        .name      = "C0",
        .step.data = 0x00002ca6,
    },
    {
        .id        = 13,
        .name      = "C#0",
        .step.data = 0x00002f4e,
    },
    {
        .id        = 14,
        .name      = "D0",
        .step.data = 0x0000321e,
    },
    {
        .id        = 15,
        .name      = "D#0",
        .step.data = 0x00003519,
    },
    {
        .id        = 16,
        .name      = "E0",
        .step.data = 0x00003841,
    },
    {
        .id        = 17,
        .name      = "F0",
        .step.data = 0x00003b9a,
    },
    {
        .id        = 18,
        .name      = "F#0",
        .step.data = 0x00003f25,
    },
    {
        .id        = 19,
        .name      = "G0",
        .step.data = 0x000042e6,
    },
    {
        .id        = 20,
        .name      = "G#0",
        .step.data = 0x000046e0,
    },
    {
        .id        = 21,
        .name      = "A0",
        .step.data = 0x00004b17,
    },
    {
        .id        = 22,
        .name      = "A#0",
        .step.data = 0x00004f8f,
    },
    {
        .id        = 23,
        .name      = "B0",
        .step.data = 0x0000544a,
    },
    {
        .id        = 24,
        .name      = "C1",
        .step.data = 0x0000594d,
    },
    {
        .id        = 25,
        .name      = "C#1",
        .step.data = 0x00005e9c,
    },
    {
        .id        = 26,
        .name      = "D1",
        .step.data = 0x0000643c,
    },
    {
        .id        = 27,
        .name      = "D#1",
        .step.data = 0x00006a32,
    },
    {
        .id        = 28,
        .name      = "E1",
        .step.data = 0x00007083,
    },
    {
        .id        = 29,
        .name      = "F1",
        .step.data = 0x00007734,
    },
    {
        .id        = 30,
        .name      = "F#1",
        .step.data = 0x00007e4a,
    },
    {
        .id        = 31,
        .name      = "G1",
        .step.data = 0x000085cd,
    },
    {
        .id        = 32,
        .name      = "G#1",
        .step.data = 0x00008dc1,
    },
    {
        .id        = 33,
        .name      = "A1",
        .step.data = 0x0000962f,
    },
    {
        .id        = 34,
        .name      = "A#1",
        .step.data = 0x00009f1e,
    },
    {
        .id        = 35,
        .name      = "B1",
        .step.data = 0x0000a894,
    },
    {
        .id        = 36,
        .name      = "C2",
        .step.data = 0x0000b29a,
    },
    {
        .id        = 37,
        .name      = "C#2",
        .step.data = 0x0000bd39,
    },
    {
        .id        = 38,
        .name      = "D2",
        .step.data = 0x0000c879,
    },
    {
        .id        = 39,
        .name      = "D#2",
        .step.data = 0x0000d465,
    },
    {
        .id        = 40,
        .name      = "E2",
        .step.data = 0x0000e106,
    },
    {
        .id        = 41,
        .name      = "F2",
        .step.data = 0x0000ee68,
    },
    {
        .id        = 42,
        .name      = "F#2",
        .step.data = 0x0000fc95,
    },
    {
        .id        = 43,
        .name      = "G2",
        .step.data = 0x00010b9a,
    },
    {
        .id        = 44,
        .name      = "G#2",
        .step.data = 0x00011b83,
    },
    {
        .id        = 45,
        .name      = "A2",
        .step.data = 0x00012c5f,
    },
    {
        .id        = 46,
        .name      = "A#2",
        .step.data = 0x00013e3c,
    },
    {
        .id        = 47,
        .name      = "B2",
        .step.data = 0x00015128,
    },
    {
        .id        = 48,
        .name      = "C3",
        .step.data = 0x00016534,
    },
    {
        .id        = 49,
        .name      = "C#3",
        .step.data = 0x00017a72,
    },
    {
        .id        = 50,
        .name      = "D3",
        .step.data = 0x000190f3,
    },
    {
        .id        = 51,
        .name      = "D#3",
        .step.data = 0x0001a8ca,
    },
    {
        .id        = 52,
        .name      = "E3",
        .step.data = 0x0001c20d,
    },
    {
        .id        = 53,
        .name      = "F3",
        .step.data = 0x0001dcd0,
    },
    {
        .id        = 54,
        .name      = "F#3",
        .step.data = 0x0001f92a,
    },
    {
        .id        = 55,
        .name      = "G3",
        .step.data = 0x00021734,
    },
    {
        .id        = 56,
        .name      = "G#3",
        .step.data = 0x00023707,
    },
    {
        .id        = 57,
        .name      = "A3",
        .step.data = 0x000258bf,
    },
    {
        .id        = 58,
        .name      = "A#3",
        .step.data = 0x00027c78,
    },
    {
        .id        = 59,
        .name      = "B3",
        .step.data = 0x0002a250,
    },
    {
        .id        = 60,
        .name      = "C4",
        .step.data = 0x0002ca69,
    },
    {
        .id        = 61,
        .name      = "C#4",
        .step.data = 0x0002f4e4,
    },
    {
        .id        = 62,
        .name      = "D4",
        .step.data = 0x000321e6,
    },
    {
        .id        = 63,
        .name      = "D#4",
        .step.data = 0x00035195,
    },
    {
        .id        = 64,
        .name      = "E4",
        .step.data = 0x0003841a,
    },
    {
        .id        = 65,
        .name      = "F4",
        .step.data = 0x0003b9a0,
    },
    {
        .id        = 66,
        .name      = "F#4",
        .step.data = 0x0003f254,
    },
    {
        .id        = 67,
        .name      = "G4",
        .step.data = 0x00042e68,
    },
    {
        .id        = 68,
        .name      = "G#4",
        .step.data = 0x00046e0f,
    },
    {
        .id        = 69,
        .name      = "A4",
        .step.data = 0x0004b17e,
    },
    {
        .id        = 70,
        .name      = "A#4",
        .step.data = 0x0004f8f0,
    },
    {
        .id        = 71,
        .name      = "B4",
        .step.data = 0x000544a1,
    },
    {
        .id        = 72,
        .name      = "C5",
        .step.data = 0x000594d3,
    },
    {
        .id        = 73,
        .name      = "C#5",
        .step.data = 0x0005e9c9,
    },
    {
        .id        = 74,
        .name      = "D5",
        .step.data = 0x000643cd,
    },
    {
        .id        = 75,
        .name      = "D#5",
        .step.data = 0x0006a32b,
    },
    {
        .id        = 76,
        .name      = "E5",
        .step.data = 0x00070834,
    },
    {
        .id        = 77,
        .name      = "F5",
        .step.data = 0x00077340,
    },
    {
        .id        = 78,
        .name      = "F#5",
        .step.data = 0x0007e4a9,
    },
    {
        .id        = 79,
        .name      = "G5",
        .step.data = 0x00085cd1,
    },
    {
        .id        = 80,
        .name      = "G#5",
        .step.data = 0x0008dc1e,
    },
    {
        .id        = 81,
        .name      = "A5",
        .step.data = 0x000962fc,
    },
    {
        .id        = 82,
        .name      = "A#5",
        .step.data = 0x0009f1e0,
    },
    {
        .id        = 83,
        .name      = "B5",
        .step.data = 0x000a8942,
    },
    {
        .id        = 84,
        .name      = "C6",
        .step.data = 0x000b29a6,
    },
    {
        .id        = 85,
        .name      = "C#6",
        .step.data = 0x000bd392,
    },
    {
        .id        = 86,
        .name      = "D6",
        .step.data = 0x000c879a,
    },
    {
        .id        = 87,
        .name      = "D#6",
        .step.data = 0x000d4656,
    },
    {
        .id        = 88,
        .name      = "E6",
        .step.data = 0x000e1069,
    },
    {
        .id        = 89,
        .name      = "F6",
        .step.data = 0x000ee680,
    },
    {
        .id        = 90,
        .name      = "F#6",
        .step.data = 0x000fc953,
    },
    {
        .id        = 91,
        .name      = "G6",
        .step.data = 0x0010b9a2,
    },
    {
        .id        = 92,
        .name      = "G#6",
        .step.data = 0x0011b83c,
    },
    {
        .id        = 93,
        .name      = "A6",
        .step.data = 0x0012c5f9,
    },
    {
        .id        = 94,
        .name      = "A#6",
        .step.data = 0x0013e3c0,
    },
    {
        .id        = 95,
        .name      = "B6",
        .step.data = 0x00151285,
    },
    {
        .id        = 96,
        .name      = "C7",
        .step.data = 0x0016534c,
    },
    {
        .id        = 97,
        .name      = "C#7",
        .step.data = 0x0017a725,
    },
    {
        .id        = 98,
        .name      = "D7",
        .step.data = 0x00190f34,
    },
    {
        .id        = 99,
        .name      = "D#7",
        .step.data = 0x001a8cac,
    },
    {
        .id        = 100,
        .name      = "E7",
        .step.data = 0x001c20d2,
    },
    {
        .id        = 101,
        .name      = "F7",
        .step.data = 0x001dcd01,
    },
    {
        .id        = 102,
        .name      = "F#7",
        .step.data = 0x001f92a6,
    },
    {
        .id        = 103,
        .name      = "G7",
        .step.data = 0x00217345,
    },
    {
        .id        = 104,
        .name      = "G#7",
        .step.data = 0x00237078,
    },
    {
        .id        = 105,
        .name      = "A7",
        .step.data = 0x00258bf2,
    },
    {
        .id        = 106,
        .name      = "A#7",
        .step.data = 0x0027c780,
    },
    {
        .id        = 107,
        .name      = "B7",
        .step.data = 0x002a250b,
    },
    {
        .id        = 108,
        .name      = "C8",
        .step.data = 0x002ca698,
    },
    {
        .id        = 109,
        .name      = "C#8",
        .step.data = 0x002f4e4b,
    },
    {
        .id        = 110,
        .name      = "D8",
        .step.data = 0x00321e68,
    },
    {
        .id        = 111,
        .name      = "D#8",
        .step.data = 0x00351958,
    },
    {
        .id        = 112,
        .name      = "E8",
        .step.data = 0x003841a5,
    },
    {
        .id        = 113,
        .name      = "F8",
        .step.data = 0x003b9a03,
    },
    {
        .id        = 114,
        .name      = "F#8",
        .step.data = 0x003f254d,
    },
    {
        .id        = 115,
        .name      = "G8",
        .step.data = 0x0042e68a,
    },
    {
        .id        = 116,
        .name      = "G#8",
        .step.data = 0x0046e0f0,
    },
    {
        .id        = 117,
        .name      = "A8",
        .step.data = 0x004b17e4,
    },
    {
        .id        = 118,
        .name      = "A#8",
        .step.data = 0x004f8f01,
    },
    {
        .id        = 119,
        .name      = "B8",
        .step.data = 0x00544a17,
    },
    {
        .id        = 120,
        .name      = "C9",
        .step.data = 0x00594d30,
    },
    {
        .id        = 121,
        .name      = "C#9",
        .step.data = 0x005e9c96,
    },
    {
        .id        = 122,
        .name      = "D9",
        .step.data = 0x00643cd1,
    },
    {
        .id        = 123,
        .name      = "D#9",
        .step.data = 0x006a32b0,
    },
    {
        .id        = 124,
        .name      = "E9",
        .step.data = 0x0070834b,
    },
    {
        .id        = 125,
        .name      = "F9",
        .step.data = 0x00773407,
    },
    {
        .id        = 126,
        .name      = "F#9",
        .step.data = 0x007e4a9b,
    },
    {
        .id        = 127,
        .name      = "G9",
        .step.data = 0x0085cd15,
    },
};
