name: kicad
on:
  push:
    paths:
      - '.github/workflows/kicad.yaml'
      - 'pcb/**'
  workflow_dispatch:

jobs:
  kicad:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check out InteractiveHtmlBom
        uses: actions/checkout@v2
        with:
          repository: openscopeproject/InteractiveHtmlBom
          ref: 95a37d306531de721f40341e17a6e397eafeef4d
          path: InteractiveHtmlBom

      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:kicad/kicad-6.0-releases
          sudo apt update
          sudo apt install -y --no-install-recommends kicad

      - name: Generate interactive BOMs
        run: |
          python3 ./InteractiveHtmlBom/InteractiveHtmlBom/generate_interactive_bom.py \
              --dark-mode \
              --no-browser \
              --dest-dir ../build/ \
              --name-format "%f" \
              --include-tracks \
              --include-nets \
              "./pcb/pico-synth.kicad_pcb"
          tar \
              -cJvf "pico-synth-bom-$(date -u '+%Y%m%d%H%M%S').tar.xz" \
              -C "./build" \
              .
        env:
          INTERACTIVE_HTML_BOM_NO_DISPLAY: "1"

      - name: Upload interactive BOMs
        run: |
          curl "${{ secrets.DISTFILES_URL }}" \
              -F "file=@$(ls -1 pico-synth-bom-* | head -n 1)" \
              -F "project=pico-synth-bom" \
              -F "version=$(ls -1 pico-synth-bom-* | head -n 1 | cut -d- -f4 | cut -d. -f1)" \
              -F "sha512=$(sha512sum pico-synth-bom-*)" \
              -F "extract=true"
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
